# Generated by Django 4.0.4 on 2022-05-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnlight',
            name='stateint',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
